spring:
  datasource:
    url: jdbc:h2:mem:credit_application_system_db
    password: 1234
    username: admin

  jpa:
    show-sql: true
    hibernate:
      #ddl-auto: create-drop    -> removido pelo uso das migrations com flyway
      properties:             # -> adicionado pelo uso das migrations com flyway
        hibernate.format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false


springdoc:
  swagger-ui:
    path: /swagger-ui.html

